server:
  port: 8082
spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/authservice
    username: postgres
    password: postgres
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: s.ishimwegabin@gmail.com
    password: eupwhwzjzzbbutsm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # distributed tracing with zipkin
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: kafka
  sleuth:
    sample:
      probability: 1.0 # send all 100% requests to zipkin
  cloud:
    compatibility-verifier:
      enabled: false

  # kafka properties
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: auth-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    topic:
      name: profile-event

#  cloud:
#    stream:
#      function:
#        definition: sendProfileSupplier; profileEventConsumer
#      bindings:
#        sendProfileSupplier-out-0: ## -out-: producer
#          destination: auth-event # topic
#        profileEventConsumer-in-out: ## -in-: consumer
#          destination: profile-event # topic

# Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    prefer-ip-address: true


app:
  jwt:
    secret: 5v8y/BE(H+MbQeThWmZq4t6w9z$C&F)
    expiration_time: 86400000 # 1 day
    refresh_token:
      expiration_time: 604800000 # 7 days
  url: 138.68.107.35

twilio:
  account_sid: AC9871796fd39b8bd098d5103efedac2a8
  auth_token: b6c54c0bc0fa1edf0e944e878da29aac
  trial_number: +16612623772