server:
  port: 8081

# Eureka Server
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      ## Auth Service Route
      - id: auth-service
        uri: lb://auth-service # used lb to allow client side to do some load balancing
        predicates:
          - Path= /api/v1/auth/**

      ## Account Service Route
      - id: account-service
        uri: lb://account-service # used lb to allow client side to do some load balancing
        predicates:
          - Path= /api/v1/account/**

      ## Profile Service Route
      - id: profile-service
        uri: lb://profile-service # used lb to allow client side to do some load balancing
        predicates:
          - Path= /api/v1/profile/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    #            route:
    #              RouteDefinitionRouteLocator: INFO
    #            nodeValue: TRACE
    ## ROOT LOGGER OF THE WHOLE APPLICATION
    root: INFO